### ISSUE TITLE
ListCharacterRequest

### ISSUE THREAD

**Issue by ZipfSebastian** [balazshorvath/NorocBackend#16]
If i send character list request i don't become answer from server:
At server console log: invalid request

Request data:
{"type":"ListCharacterRequest","session":"jnPcLVWivrDkM5XEer6r36P2dIw2QUMd"}

Nullpointer at the Reconnect error issue.

**Comment by balazshorvath** [comment]
Seems to be fixed, with adding the reconnect feature

**Comment by balazshorvath** [comment]
The error came from this: https://github.com/balazshorvath/NorocBackend/issues/15
