### ISSUE TITLE
ListWorldsError

### ISSUE THREAD

**Issue by ZipfSebastian** [balazshorvath/NorocBackend#17]
Sended:
{"type":"ListWorldsRequest","session":"ud1x9IZDpq3qEeHpMtfmpDoReXfzMkRe"}

Response:
{"type":"ErrorResponse","code":211,"message":"You need to login first!"}

I logged in but server response is not a world list

And the same nullpointer on console log!

**Comment by balazshorvath** [comment]
Seems to be fixed, with adding the reconnect feature

**Comment by balazshorvath** [comment]
Error was related to this: https://github.com/balazshorvath/NorocBackend/issues/15
